# Global JasperReports configuration
net.sf.jasperreports.extension.registry.factory.pdf=net.sf.jasperreports.pdf.PdfExtensionsRegistryFactory
net.sf.jasperreports.extension.registry.factory.functions=net.sf.jasperreports.functions.FunctionsRegistryFactory
net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
